# -e "ACCEPT_EULA=Y" 
# -e "SA_PASSWORD=Metatiadmin%%%%" 
# -e "MSSQL_PID=Express" 
# --cap-add SYS_PTRACE 
# -p 11433:1433 
# -d microsoft/mssql-server-linux:2017-latest
version: '3'
services:
  backend:
    build: ./Meta.TI.Project
        ports:
            - "5000:5000"
        depends_on:
            - db
  db:
    image: microsoft/mssql-server-linux:2017-latest
    env: 
      - ACCEPT_EULA=Y    
      - SA_PASSWORD=Metatiadmin%%%%
      - MSSQL_PID=Express
    ports: 
      - 11433:1433